### ISSUE TITLE
BestBuy February 2021

### ISSUE THREAD

**Issue by Zepto48** [TreborNamor/Agressive-Bots#21]
Stock drops are now made in waves for a few minutes until sold out. The add to cart button Must now be pressed once to initiate process, and a second time when more stock is made available to actually add to cart. The bot worked perfectly and instantly for the first button press as soon as news stock was available but did not press the second time. 

This was for the February 25, 2021 
3000 series stock drop from BestBuy

**Comment by TreborNamor** [comment]
this script might help you with bestbuy pre-order queue system. 

https://github.com/TreborNamor/Agressive-Bestbuy-Bot/blob/main/bestbuy-preorder.py

**Comment by Zepto48** [comment]
Great! 

I just want to thank you for this project! Not only am I confident that this will help me acquire a GPU, but reviewing your code also helping me understand web scraping and automation better for other applications! 

The only other issue that I've had with this code is that sometimes the webpage would fail to reload after a couple of hours of running and the code would end with an error message. I tried fixing this by increasing the page reload wait time and making the script wait an extra second before reloading the page, which made it much more reliable (but still possible to stall). Please ignore this if that was resolved after your update to the script, but otherwise is there a way to fix this, or is this an issue on BestBuy's end? 

Endless Thanks!
